In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import RobustScaler, OneHotEncoder, LabelEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn import metrics as sm
from sklearn.tree import DecisionTreeClassifier
from warnings import filterwarnings
filterwarnings('ignore')
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier, VotingClassifier

from sklearn.naive_bayes import GaussianNB

In [2]:
df=pd.read_csv(r"C:\Users\ASUS\Downloads\archive (2)\WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head(3)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes

In [3]:
pd.set_option('display.max_columns', None)
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:


df['TotalCharges']=pd.to_numeric(df['TotalCharges'],errors='coerce')

In [5]:
def f(x):
    if x=='Month-to-month':
        return 0
    elif x=='Two year':
        return 1
    else:
        return 2


df['Contract']=df['Contract'].apply(f).astype(int)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   int64
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(3), object(16)
memory usage: 1.1+ MB

In [7]:
df=df.drop(columns=['customerID'])

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Churn']), df[['Churn']], 
                                                    test_size=0.25, random_state=25)

In [9]:
imputer=SimpleImputer(strategy='median')
X_train[['TotalCharges']]=imputer.fit_transform(X_train[['TotalCharges']])
X_test[['TotalCharges']]=imputer.transform(X_test[['TotalCharges']])

In [10]:
X_train[['TotalCharges']].isna().sum()

TotalCharges    0
dtype: int64

In [11]:
preprocess=ColumnTransformer([
    ("Scaling",RobustScaler(),['SeniorCitizen','tenure','MonthlyCharges','TotalCharges']),

    ('Nominal',OneHotEncoder(dtype=int),['gender','Partner','Dependents','PhoneService','OnlineSecurity','OnlineBackup','DeviceProtection',
                                'TechSupport','StreamingTV','StreamingMovies','PaperlessBilling','MultipleLines','InternetService',
                                'PaymentMethod'])
                                
])

In [12]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,0,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,2,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,0,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,2,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,0,Yes,Electronic check,70.70,151.65,Yes

In [13]:
log=LogisticRegression()
knn=KNeighborsClassifier(n_neighbors=5)
rfc=RandomForestClassifier(max_depth=6,n_estimators=200)

vc=VotingClassifier([('lr',log),('knn',knn),('rfc',rfc)])

In [14]:
from imblearn.over_sampling import RandomOverSampler

ros=RandomOverSampler(random_state=25)

X_over, y_over=ros.fit_resample(X_train,y_train)

print(y_train.value_counts())
print(y_over.value_counts())

Churn
No       3892
Yes      1390
Name: count, dtype: int64
Churn
No       3892
Yes      3892
Name: count, dtype: int64

In [15]:
model=Pipeline([('preprocess',preprocess),('modelling',vc)])   #Gaussiannb() also can be used

#model.fit(X_train,y_train)

model.fit(X_over,y_over)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('Scaling', RobustScaler(),
                                                  ['SeniorCitizen', 'tenure',
                                                   'MonthlyCharges',
                                                   'TotalCharges']),
                                                 ('Nominal',
                                                  OneHotEncoder(dtype=<class 'int'>),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'PaperlessBilling',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'PaymentMethod'])])),
                ('modelling',
                 VotingClassifier(estimators=[('lr', LogisticRegression()),
                                              ('knn', KNeighborsClassifier()),
                                              ('rfc',
                                               RandomForestClassifier(max_depth=6,
                                                                      n_estimators=200))]))])

In [16]:
sm.balanced_accuracy_score(y_test,model.predict(X_test))

0.7692622109894833

In [17]:
sm.balanced_accuracy_score(y_over,model.predict(X_over))

0.7894398766700925